In [22]:
from bs4 import BeautifulSoup
import urllib.request as req
import pandas as pd

url = 'https://www.opentable.com/r/the-woo-new-york'
html = req.urlopen(url)
soup = BeautifulSoup(html, 'html.parser')

In [23]:
# Before 'decompose()'
soup.find_all(class_='oc-reviews-954a6007')[2].text

'vipHM110'

In [24]:
#review-OT-1023310-23377-110015810691 > div.oc-reviews-9f330471 > div.oc-reviews-954a6007 > span.oc-reviews-42b9159d
for t in soup.find_all(class_='oc-reviews-42b9159d'):
    t.decompose()

In [25]:
soup.find_all(class_='oc-reviews-42b9159d')

[]

In [26]:
soup.find_all(class_='oc-reviews-954a6007')[2].text

'HM110'

In [33]:
reviewer = []

r1 = [soup.find_all(class_='oc-reviews-954a6007')[n].text for n in range(0, 40)]
reviewer.extend(r1)
reviewer

['CarB',
 'Mateo',
 'HM110',
 'OpenTable Diner',
 'HunterJ',
 'MatthewH',
 'Livetoeat',
 'Susannam2',
 'OpenTable Diner',
 'OpenTable Diner',
 'dsf45',
 'Rick',
 'rafaelp',
 'AnthonyD',
 'Naama',
 'OpenTable Diner',
 'OlgaK',
 'OpenTable Diner',
 'smc18',
 'LaurenD',
 'KimC',
 'PriyuG',
 'OpenTable Diner',
 'JohnP',
 'OpenTable Diner',
 'OpenTable Diner',
 'ReyJaiteh',
 'OpenTable Diner',
 'OpenTable Diner',
 'NatashaC',
 'OpenTable Diner',
 'TastyKoreanJoint',
 'OpenTable Diner',
 'JimD',
 'AsliP',
 'SophiannL',
 'OpenTable Diner',
 'NY2World',
 'FlorenceG',
 'OpenTable Diner']

In [38]:
review = []
r2 = [soup.find_all(class_="reviewBodyContainer oc-reviews-8107696f")[n].text for n in range(0,40)]
review.extend(r2)

In [35]:
import pandas as pd

In [36]:
pd.DataFrame({"Reveiwer": reviewer, "Review": review})

            Reveiwer                                             Review
0               CarB                                   Love this place!
1              Mateo  Food was great, servers were fast paced and di...
2              HM110                                       Great place.
3    OpenTable Diner  I am a fan of Woo Lae Oak and have been patien...
4            HunterJ  Very yummy and piping hot! I loved the food an...
5           MatthewH                               Wonderful experience
6          Livetoeat  Seemed pricey and lacked ambiance. Waiter seem...
7          Susannam2  Food was amazing. My first time here as was so...
8    OpenTable Diner  It was amazing everything was wonderful servic...
9    OpenTable Diner  The food was excellent but they only gave 3 ba...
10             dsf45  The Woo was great.  The food was delicious and...
11              Rick  The Korean food was delicious, service OK.  Th...
12           rafaelp  Great food. Great value. There is room for imp...
13          AnthonyD  The food was undeniably awesome! The outdoor s...
14             Naama  Came here with a group of 7 friends and had a ...
15   OpenTable Diner         Great food, great music, amazing drinks!!!
16             OlgaK  In love with food at the Woo! Everything that ...
17   OpenTable Diner  My wife, daughters and I visited NYC for the f...
18             smc18                           Good food but expensive.
19           LaurenD  Great food and beverages. Manny and team alway...
20              KimC  We had a great experience and will definitely ...
21            PriyuG  This is a great upscale alternative to Korean ...
22   OpenTable Diner  Great experience, socially distanced. Great wa...
23             JohnP              Fantastic food!! Cant wait to go back
24   OpenTable Diner  We arrived at the Woo promptly for our reserva...
25   OpenTable Diner                       just so so. Too cold outside
26         ReyJaiteh  The food was amazing. The ambience was everyth...
27   OpenTable Diner  Food was great, drinks were nice and strong. O...
28   OpenTable Diner  Food was delicious, it was my first time at a ...
29          NatashaC  Amazing food and service. Also very beautiful ...
30   OpenTable Diner  Our server (I unfortunately didn’t catch his n...
31  TastyKoreanJoint  The food here was very good. Short rib dumplin...
32   OpenTable Diner  AWESOME FOOD! went for outdoor dining and love...
33              JimD  Had a great time! I would recommend The Woo to...
34             AsliP  We had a fab time: food, drinks, service and h...
35         SophiannL  For outside dining, I think it would be best t...
36   OpenTable Diner  Very nice spot, the food & ambiance was deligh...
37          NY2World  Definitely one of our favorite Korean restaura...
38         FlorenceG  Just wonderful all around ! We truly enjoyed!!...
39   OpenTable Diner  Just all around incredible will definitely be ...

In [37]:
pages = range(1,8)
list(pages)

[1, 2, 3, 4, 5, 6, 7]

In [40]:
reviewers = []
reviews = []


for p in pages:
    url = "https://www.opentable.com/r/the-woo-new-york?page=" + str(p) ## p 는 int 자료형이라서 str로 바꿔주면서 더하기를 해야 같이 텍스트로 인식된다
    html = req.urlopen(url)
    doc = BeautifulSoup(html, "html.parser")
    
    for t in doc.find_all(class_='oc-reviews-42b9159d'):
        t.decompose()
    
    end = len(doc.find_all(class_='oc-reviews-954a6007'))
    
    r1 = [doc.find_all(class_='oc-reviews-954a6007')[n].text for n in range(0, end)]
    reviewers.extend(r1)
    
    r2 = [doc.find_all(class_="reviewBodyContainer oc-reviews-8107696f")[n].text for n in range(0, end)]
    reviews.extend(r2)
    
pd.DataFrame({"Reveiwer": reviewers, "Review": reviews})

            Reveiwer                                             Review
0               CarB                                   Love this place!
1              Mateo  Food was great, servers were fast paced and di...
2              HM110                                       Great place.
3    OpenTable Diner  I am a fan of Woo Lae Oak and have been patien...
4            HunterJ  Very yummy and piping hot! I loved the food an...
..               ...                                                ...
238          PierreK  Anyone who logged time at the old Woo Lae Oak ...
239  OpenTable Diner              You have to cook everything yourself.
240  OpenTable Diner  After a long 10 year wait we were SO happy to ...
241  OpenTable Diner                           The food was amazing!!!!
242          pakruth  Opening night - had early dinner with family. ...

[243 rows x 2 columns]