In [11]:
import requests
from bs4 import BeautifulSoup ##html 싹 가져와주는 애
from selenium import webdriver ##웹드라이버 돌려주는애
import pandas as pd
import time

webdriver_options = webdriver.ChromeOptions()
webdriver_options.add_argument('headless') ##창 띄우지 만 상태에서 알아서 해라
webdriver_options.add_argument('window-size=1920x1080') ## 창 사이즈 지정해줘야 렉 안 먹음
webdriver_options.add_argument("disable-gpu") ##크롬드라이버가 gpu 부스터를 쓰기 때문에 가끔렉 먹는거 방지용
webdriver_options.add_argument("lang=ko-KR") ##위에 코드 3개가 쓰면 영어로 전체를 돌려버려서 언어 한국말로 바꿔주기

driver = webdriver.Chrome('/Users/jonghyunkim/Downloads/chromedriver', options=webdriver_options) ##위에 정한 옵션으로 크롬을 실행하라

url = 'https://portal.korea.ac.kr/front/Intro.kpd'
driver.implicitly_wait(3) ## 드라이버 실행까지 시간이 좀 있으니 기다려 주는 역할
driver.get(url)
# driver.maximize_window() ## 창 전체화면 하기

##로그인 하기 
driver.find_element_by_name('id').send_keys('stanley41')
driver.find_element_by_name('pw').send_keys('crimson9841')
driver.find_element_by_xpath('//*[@id="loginsubmit"]').click()

driver.implicitly_wait(5) ## 로딩도 안됐는데 xpath 클릭하면 에러 뜨니까 기다려주는 역할
driver.find_element_by_xpath('//*[@id="header"]/div[2]/div/div/ul/li[4]/a').click() ##학적 졸업 클릭

driver.find_element_by_xpath('//*[@id="m127"]/a').click() ##졸업정보 클릭
driver.find_element_by_xpath('//*[@id="sm289"]/a').click() ##졸업사정표 클릭

time.sleep(5) ## 잠시 기다려!

from selenium.webdriver.common.alert import Alert ##경고창 뜨는거 제어하는 Alert 함수 불러오기
Alert(driver).accept() ##경고창에 확인버튼 눌러주는 역할 ---------

time.sleep(3) ## 잠시 기다려!

driver.switch_to.frame('_component') ## iframe 안에 있어서 테이블이 있어서 탐색이 안되는 문제를 해결 --> 이 경우는 iframe 안에 이름이 _component라서 그렇게 찾아준거

soup = BeautifulSoup(driver.page_source, 'lxml') ## parsing 한거


## 이제 표들에서 데이터를 끌어와야 한다
element_table = soup.find_all(name='table')
table = pd.read_html(str(element_table))


driver.quit()

print(type(table[0]))
table[2]

<class 'pandas.core.frame.DataFrame'>

    이수구분   구분               영역명  최소이수학점  최대인정학점  성적학점  수강학점  재수강학점
0     교양   이수            1학년세미나     1.0     NaN   1.0   NaN    NaN
1     교양   이수             정보적사고     1.0     NaN   1.0   NaN    NaN
2     교양   이수            전공관련교양    12.0     NaN  12.0   NaN    NaN
3     교양   이수              핵심교양     9.0     NaN  12.0   NaN    NaN
4     교양   이수              선수과목     3.0     NaN   3.0   NaN    NaN
5     교양   이수             사고와표현     4.0     NaN   4.0   NaN    NaN
6     교양   이수  ACADEMIC ENGLISH     2.0     4.0   2.0   NaN    NaN
7     교양   이수              일반교양     NaN     NaN  15.0   NaN    NaN
8   전공선택  미이수              전공선택    15.0     NaN  12.0   NaN    NaN
9   전공필수  미이수              전공필수    24.0     NaN  15.0   NaN    NaN
10   NaN   이수     다중전공으로 인정된 과목     NaN     NaN   NaN   NaN    NaN
11   NaN   이수   제1전공과 동시 인정불가과목     NaN     NaN   NaN   NaN    NaN
12   NaN  NaN                합계     NaN     NaN  77.0   NaN    NaN

In [12]:
table.to_excel('졸업사정표.xlsm')

AttributeError: 'list' object has no attribute 'to_excel'